name: pieces_product_checklists
description:
  A library for working with Pieces APIs and Manual testing checklists
version: 0.0.1
homepage: https://github.com/pieces-app/Pieces-Product-Checklists

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter_highlight:
  runtime_client:
    git:
      url: git@github.com:open-runtime/runtime_client.git
  file_picker:
  googleapis: ^8.0.0
  googleapis_auth: ^1.3.0
  http: ^0.13.0
  meta: ^1.3.0
  collection: ^1.15.0
  openapi_dart_common: ^4.1.1
  connector_openapi:
    git:
      url: git@github.com:open-runtime/generated_runtime.git
      path: sdk/http/dart/connector
  core_openapi:
    git:
      url: git@github.com:open-runtime/generated_runtime.git
      path: sdk/http/dart/core
  #      url: git@bitbucket.org:pi3c3s/isomorphic_openapi.git
  #      path: ./core/dart/
  string_stats: ^0.1.0
  card_slider: ^1.0.5
  carousel_slider: ^4.2.1
  flutter_3d_obj: ^0.0.6
  flutter_cube: ^0.1.1
#  animations: ^2.0.7
dev_dependencies:
  pedantic: ^1.11.1
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  mockito:

  flutter_test:
    sdk: flutter
  test:
flutter:


  uses-material-design: true

fonts:
  - family: RobotoMono
    fonts:
      - asset: assets/fonts/RobotoMono-Regular.ttf
          -images/piecesLogo.png

    assets:
      -assets/piecesLogo.png
      -assets/dart.jpg
      -assets/